import type { CSSProperties } from "react";

export const s: Record<string, CSSProperties> = {
  root: {
    display: "flex",
    height: "100vh",
    background: "var(--bg, #0f0d0c)",
    color: "var(--text, #c8b89a)",
    fontFamily: "var(--mono, 'JetBrains Mono', monospace)",
    fontSize: "13px",
    overflow: "hidden",
  },
  sidebar: {
    width: "210px",
    minWidth: "210px",
    background: "var(--sidebar-bg, #161210)",
    borderRight: "1px solid var(--border, #2e2a27)",
    padding: "20px 16px",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    overflowY: "auto",
  },
  sidebarTitle: {
    margin: "0 0 10px",
    fontSize: "12px",
    fontWeight: 700,
    color: "var(--text-h, #e0cdb0)",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  fieldLabel: {
    fontSize: "11px",
    color: "var(--text-d, #7a6e62)",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    marginBottom: "2px",
  },
  select: {
    background: "var(--code-bg, #1e1a17)",
    border: "1px solid var(--border, #2e2a27)",
    borderRadius: "4px",
    color: "var(--text, #c8b89a)",
    padding: "5px 8px",
    fontFamily: "var(--mono, monospace)",
    fontSize: "12px",
    width: "100%",
    marginBottom: "10px",
    outline: "none",
    cursor: "pointer",
  },
  mapId: {
    background: "var(--code-bg, #1e1a17)",
    border: "1px solid var(--border, #2e2a27)",
    borderRadius: "4px",
    color: "var(--text-d, #7a6e62)",
    padding: "5px 8px",
    fontSize: "12px",
    marginBottom: "6px",
    letterSpacing: "0.04em",
  },
  shapeToggle: {
    display: "flex",
    gap: "4px",
    marginBottom: "10px",
  },
  shapeBtn: {
    flex: 1,
    background: "transparent",
    border: "1px solid var(--border, #2e2a27)",
    borderRadius: "4px",
    color: "var(--text-d, #7a6e62)",
    fontFamily: "var(--mono, monospace)",
    fontSize: "11px",
    padding: "4px 0",
    cursor: "pointer",
    letterSpacing: "0.04em",
    transition: "all 0.1s ease",
  },
  shapeBtnActive: {
    background: "var(--code-bg, #2a2623)",
    border: "1px solid var(--text-d, #7a6e62)",
    color: "var(--text, #c8b89a)",
  },
  sectionLabel: {
    margin: "4px 0",
    fontSize: "11px",
    color: "var(--text-d, #5a5048)",
    lineHeight: 1.5,
  },
  markerGrid: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    marginTop: "4px",
  },
  markerRow: {
    display: "flex",
    alignItems: "center",
    gap: "7px",
  },
  badge: {
    width: "26px",
    height: "26px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "var(--mono, monospace)",
    fontSize: "11px",
    fontWeight: 700,
    cursor: "pointer",
    flexShrink: 0,
    transition: "all 0.1s ease",
  },
  coords: {
    flex: 1,
    fontSize: "10px",
    color: "var(--text-d, #8a7e72)",
    letterSpacing: "0.02em",
    transition: "opacity 0.15s",
    fontVariantNumeric: "tabular-nums",
  },
  toggleBtn: {
    border: "1px solid var(--border, #2e2a27)",
    borderRadius: "3px",
    fontFamily: "var(--mono, monospace)",
    fontSize: "10px",
    padding: "2px 5px",
    cursor: "pointer",
    letterSpacing: "0.04em",
  },
  resetBtn: {
    marginTop: "10px",
    background: "transparent",
    border: "1px solid var(--border, #3a3230)",
    borderRadius: "4px",
    color: "var(--text-d, #6a5e52)",
    fontFamily: "var(--mono, monospace)",
    fontSize: "11px",
    padding: "6px",
    cursor: "pointer",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  main: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  arenaWrap: {
    flex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "24px",
    minHeight: 0,
    width: "100%",
    boxSizing: "border-box",
  },
  canvas: {
    width: "100%",
    height: "100%",
    maxWidth: "100%",
    maxHeight: "100%",
    objectFit: "contain",
    display: "block",
    touchAction: "none",
    transition: "border-radius 0.2s ease, opacity 0.15s",
  },
  jsonPane: {
    flexShrink: 0,
    height: "220px",
    borderTop: "1px solid var(--border, #2e2a27)",
    background: "var(--code-bg, #111009)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  jsonHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "6px 12px",
    borderBottom: "1px solid var(--border, #2e2a27)",
    flexShrink: 0,
  },
  jsonHeaderLeft: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  jsonLabel: {
    fontFamily: "var(--mono, monospace)",
    fontSize: "12px",
    color: "var(--text, #c8b89a)",
  },
  errorBadge: {
    fontSize: "10px",
    color: "#e05555",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    opacity: 0.8,
  },
  copyBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "var(--text, #c8b89a)",
    padding: "2px 4px",
    borderRadius: "4px",
    fontFamily: "var(--mono, monospace)",
    fontSize: "12px",
    lineHeight: 1,
  },
  jsonPre: {
    flex: 1,
    margin: 0,
    padding: "12px 16px",
    overflowY: "auto",
    background: "transparent",
    border: "2px solid transparent",
    borderRadius: 0,
    cursor: "text",
    transition: "border-color 0.15s",
    textAlign: "left",
  },
  jsonCode: {
    fontSize: "12px",
    fontWeight: 600,
    background: "none",
    padding: 0,
    borderRadius: 0,
    display: "block",
    color: "var(--shiki-color-text, #8a9e7a)",
    fontFamily: "var(--mono, monospace)",
    lineHeight: 1.6,
    whiteSpace: "pre",
    textAlign: "left",
  },
  jsonTextarea: {
    flex: 1,
    margin: 0,
    padding: "12px 16px",
    background: "transparent",
    border: "none",
    outline: "none",
    resize: "none",
    color: "var(--shiki-color-text, #8a9e7a)",
    fontFamily: "var(--mono, monospace)",
    fontSize: "12px",
    fontWeight: 600,
    lineHeight: 1.6,
    whiteSpace: "pre",
    overflowY: "auto",
    width: "100%",
    boxSizing: "border-box",
    textAlign: "left",
  },
};
